import React from 'react';

const Start = () => {
    return (
        <div>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
            Welcome
            <br/>
        </div>
    );
};

export default Start;