export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const HOME_PAGE = '/'
export const COMPANY_LIST = '/companyList'
export const USER_LIST = '/userList'
export const USER_ADD = '/userAdd'
export const ERROR = '/error'
export const COMPANY_ADD = '/companyAdd'
export const USER_EDIT = '/userEdit'
export const USER_PROFILE = '/userProfile'
export const COMPANY_PROFILE = '/companyEdit'
export const REG_LINK = '/registraration_link/'
export const INDICATOR_RESULT = '/indicatorResult'
export const NEW_PASSWORD = '/newPassword'
export const ACTIVATION = '/activate'
export const FORGOT_PASSWPRD = '/forgotPassword'
export const SETTINGS = '/settings'
export const SETTINGS_NOTIFICATION = '/settings/notification'
export const SETTINGS_INTEGRATION = '/settings/integration'
export const NEW_DATA = '/indicator_add_value'
export const INDICATOR_LIST = '/indicator/list'
export const INDICATOR_MEMBER = '/indicator/member'
export const AMO_INTEGRATION = '/settings/integration/amo'
export const INEGTRATION_NEW = '/indicator/new'

//export const URL_BASE = 'https://localhost:8080'
export const URL_BASE = 'https://rmsys.info:8080'

export const AMO_SECRET = "TmGlWbEkSD6rWEhSpj99BFpqOARiGOxK3Yf6InB7KsVBs7OeUiJuK1Bfcjzu86PW"
export const AMO_ID ="dbba0587-f04a-4453-b5e9-6894ccca3089"

export const URL_LOGIN = URL_BASE + '/app/login'
export const URL_REGISTRATION_ROUTE = '/app/registration'
export const URL_REFRESH = URL_BASE + '/app/refreshtoken'
export const URL_FORGOT_PASSWPRD = URL_BASE + '/app/forgot'
export const URL_NEW_PASSWORD = URL_BASE + '/app/newPassword'
export const URL_ACTIVATION = URL_BASE + '/app/activate'

export const URL_ALL_USER = URL_BASE + '/app/user/all'
export const URL_EDIT_USER = URL_BASE + '/app/user/editUser'
export const URL_USER_COMPANYNAME = URL_BASE + '/app/user/userCompanyName'
export const URL_NEW_USER = URL_BASE + '/app/user/addNewUser'
export const URL_STATUS_USER = URL_BASE + '/app/user/status'
export const URL_ROLE_USER = URL_BASE + '/app/user/role'
export const URL_SEARCH_USER = URL_BASE + '/app/user/search'
export const URL_DELETE_USER = URL_BASE + '/app/user/delete'
export const URL_INDICATOR_RESULT = '/app/user/indicatorResult'
export const URL_INDICATOR_LINKS = '/app/user/indicatorResultLinks'
export const URL_INDICATOR_RESULT_SEARCH = '/app/user/indicatorResult/search';
export const URL_INDICATOR_RESULT_NAME = '/app/user/indicatorResult/trends';
export const URL_ROLEUSER = '/app/user/getUserRole'
export const URL_PROFILE = '/app/user/profile'
export const URL_CHANGR_SETTINGS_TRENDS = '/app/user/indicatorResult/changeSetting'
export const URL_IS_ADMIN = '/app/user/isAdmin'
export const URL_GET_SETTINGS_INDICATOR = '/app/user/getIndicatorSetting'
export const URL_SETTINGS_NOTIFICATION = '/app/user/settings/notification'
export const URL_NEW_DATA = '/app/user/indicatorAddValue'

export const URL_INDICATOR_LIST = 'app/user/indicator_setting/list'
export const URL_INDICATOR_IND_MEMBER_LIST = 'app/user/indicator_setting/indMemberList'
export const URL_INDICATOR_IND_MEMBER = 'app/user/indicator_setting/member'
export const URL_INDICATOR_NEW_INFO = 'app/user/indicator_setting/new/info'
export const URL_INDICATOR_NEW = 'app/user/indicator_setting/new'



export const URL_INEGTRATION_SETTINGS = '/app/user/integration/settings'
export const URL_INEGTRATION_LIST = '/app/user/integration/list'
export const URL_INEGTRATION_NEW = '/app/user/integration/new'
export const URL_INEGTRATION_ONE = '/app/user/integration/one/'
export const URL_INEGTRATION_SET = '/app/user/integration/set'
export const URL_INEGTRATION_TEST = '/app/user/integration/test'
export const URL_INEGTRATION_DELETE = '/app/user/integration/delete'
export const URL_INEGTRATION_AMO_TEST = '/app/user/integration/settings/amo/test'
export const URL_INEGTRATION_AMO_SAVE = '/app/user/integration/settings/amo/save'
export const URL_INEGTRATION_AMO_TEST_FUNCTION = '/app/user/integration/settings/amo/testFunction'


export const URL_EDIT_CLIENT = URL_BASE + '/app/client/edit'
export const URL_ALL_CLIENTS = URL_BASE + '/app/client/all'
export const URL_ADD_CLIENTS = URL_BASE + '/app/client/addClient'
export const URL_SEARCH_CLIENTS = URL_BASE + '/app/client/search'

export const ACCESS_TOKEN = 'token'
export const REFRESH_TOKEN = 'refreshToken'
export const AUTHRIZATION_WORD = 'Bearer'
export const AUTHORIZATION = 'Authorization'
export const AUTH = 'auth'
export const USERNAME = 'username'
export const LAST_PAGE = 'lastPage'
export const REMEMBER_MY = 'remembermy'
export const AMO_INEGRATION_ID = 'idIntegration'

export const ROLE_VLADELTC = 'Владелец'
export const ROLE_USER = 'Пользователь'
export const ROLE_RUKOVOD = 'Руководитель'
