export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const HOME_PAGE = '/'
export const COMPANY_LIST = '/companyList'
export const USER_LIST = '/userList'
export const USER_ADD = '/userAdd'
export const ERROR = '/error'
export const COMPANY_ADD = '/companyAdd'
export const USER_PROFILE = '/userEdit'
export const COMPANY_PROFILE = '/companyEdit'

export const URL_BASE = 'http://localhost:8080'
export const URL_LOGIN = URL_BASE+'/app/login'
export const URL_REGISTRATION_ROUTE = '/app/registration'
export const URL_REFRESH = URL_BASE + '/app/refreshtoken'

export const URL_ALL_USER = URL_BASE + '/app/user/all'
export const URL_EDIT_USER = URL_BASE + '/app/user/profile'
export const URL_ADD_USER = URL_BASE + '/app/user/addUsers'
export const URL_STATUS_USER = URL_BASE + '/app/user/status'
export const URL_ROLE_USER = URL_BASE + '/app/user/role'
export const URL_SEARCH_USER = URL_BASE + '/app/user/search'

export const URL_EDIT_CLIENT = URL_BASE + '/app/client/edit'
export const URL_ALL_CLIENTS = URL_BASE + '/app/client/all'
export const URL_ADD_CLIENTS = URL_BASE + '/app/client/addClient'
export const URL_SEARCH_CLIENTS = URL_BASE + '/app/client/search'


export const ACCESS_TOKEN = 'accessToken'
export const REFRESH_TOKEN = 'refreshToken'
export const AUTHRIZATION_WORD = 'Bearer'
export const AUTHORIZATION = 'Authorization'
export const AUTH = 'auth'
export const USERNAME = 'username'

